### ISSUE TITLE
Babel mobule build failure

### ISSUE THREAD

**Issue by insanity54** [doomsquadairsoft/controlpointer#18]
```
[2] ERROR in ./src_client/index.js
[2] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[2] Error: Plugin/Preset files are not allowed to export objects, only functions. In /home/lbs/Documents/controlpointer/node_modules/babel-preset-es2015/lib/index.js
[2]     at createDescriptor (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
[2]     at items.map (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
[2]     at Array.map (<anonymous>)
[2]     at createDescriptors (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
[2]     at createPresetDescriptors (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
[2]     at presets (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
[2]     at mergeChainOpts (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-chain.js:320:26)
[2]     at /home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-chain.js:283:7
[2]     at buildRootChain (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/config-chain.js:120:22)
[2]     at loadPrivatePartialConfig (/home/lbs/Documents/controlpointer/node_modules/@babel/core/lib/config/partial.js:85:55)
[2]  @ multi (webpack)-dev-server/client?http://localhost:5001 (webpack)/hot/dev-server.js ./src_client/index.js main[2]
[2] ℹ ｢wdm｣: Failed to compile.
[0] [winston] Attempt to write logs with no transports {"message":"before app.service('events').create()","level":"debug"}
[0] [winston] Attempt to write logs with no transports {"level":"debug","message":"Hook Context"}
[0] [winston] Attempt to write logs with no transports {"message":"after app.service('events').create()","level":"debug"}
```

**Comment by insanity54** [comment]
Caused by a external library dependency when upgrading node_modules. Workaround is to hold off on upgrade. See #19
